feat: add article tool bar & snackbar component
twreporter/twreporter-npm-packages pull request #276
Opened 2022-05-31 08:16 UTC by Aylie-Chou

- design system
  - add SnackBar
  - support styled(component) in text/headline & text/parageaph
- article
  - add ToolBar
  - remove MobileAside

2022-06-01 02:28 UTC, duidae requested changes

2022-06-01 02:28 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +const FbShare = ({ appID }) => {
could we possibly reduce the duplicate codes of `FbShare` `LineShare` `TwitterShare` `CopyUrl` since they are quite similar?

2022-06-01 02:28 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +    <ButtonContainer onClick={() => setShowState(prevValue => !prevValue)}>
same as above (inline function prop)

2022-06-01 02:28 UTC, duidae commented on packages/react-article-components/src/components/article-page.js
> +                id="related-post-anchor"
btw, could we define `related-post-anchor` as a constant in a file (ex: anchor.js in constants/) since it's referenced by 2 separated files(`article-page.js`, `mobile-tool-bar.js`)

2022-06-01 03:42 UTC, Aylie-Chou commented on packages/react-article-components/src/components/article-page.js
> +                id="related-post-anchor"
Because `header` block may cover part of the `RelatedBlock`, the designer assign `Licence` to be the anchor.
(ref: [figma design](https://www.figma.com/file/PBIkqBtXK8q65LP9DpOUxO/%E3%80%90%E8%A8%AD%E8%A8%88%E4%BA%A4%E4%BB%98%E3%80%912022-%E8%B3%87%E8%A8%8A%E6%9E%B6%E6%A7%8B?node-id=863%3A32550))

2022-06-01 05:53 UTC, duidae commented on packages/react-article-components/src/components/article-page.js
> +                id="related-post-anchor"
I see, how about this solution for adding offset to the anchor? 
https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

2022-06-01 08:34 UTC, Aylie-Chou commented on packages/react-article-components/src/components/article-page.js
> +                id="related-post-anchor"
The offset value would be related with `universal-header` height. To decrease the dependency between two packages, I think add a comment would be help. ([bf8a5ee](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/bf8a5ee961d4f4ba286d7f2b90d0751d9c9b4e44))

2022-06-01 08:34 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +      <IconButton iconComponent=<Line /> theme={theme} />
updated ([bf8a5ee](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/bf8a5ee961d4f4ba286d7f2b90d0751d9c9b4e44))

2022-06-01 08:34 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +      <IconButton iconComponent=<Twitter /> theme={theme} />
updated ([bf8a5ee](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/bf8a5ee961d4f4ba286d7f2b90d0751d9c9b4e44))

2022-06-01 08:35 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +      <IconButton iconComponent=<Copy /> theme={theme} />
updated ([bf8a5ee](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/bf8a5ee961d4f4ba286d7f2b90d0751d9c9b4e44))

2022-06-01 08:35 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +          iconComponent=<Bookmark type={iconType} />
updated ([bf8a5ee](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/bf8a5ee961d4f4ba286d7f2b90d0751d9c9b4e44))

2022-06-01 08:35 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +        iconComponent=<Article />
updated ([bf8a5ee](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/bf8a5ee961d4f4ba286d7f2b90d0751d9c9b4e44))

2022-06-07 08:24 UTC, Aylie-Chou commented on packages/react-article-components/src/components/article-page.js
> +                id="related-post-anchor"
define `related-post-anchor` in constants/anchor.js ([1694069](https://github.com/twreporter/twreporter-npm-packages/pull/276/commits/1694069e769e685b6ec892e0d736111023c1319a))

2022-06-07 08:25 UTC, Aylie-Chou commented
updated.

- remove eslint warning
- address design change (style & animation)
- define `related-post-anchor` in constants/anchor.js

2022-06-08 07:06 UTC, duidae approved these changes

2022-06-08 07:16 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +const FbShare = ({ appID }) => {
`FbShare`, `LineShare`, `TwitterShare`, `CopyUrl` themself are simple, I cannot come out a way to merge them without loss readable.
Do you have any idea ?

2022-06-08 08:26 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +const FbShare = ({ appID }) => {
current code is fine and I tried to refactor some but the result didnt look much better.

2022-06-08 08:39 UTC, merged