fix: fix defect
twreporter/twreporter-npm-packages pull request #280
Opened 2022-06-13 13:03 UTC by Aylie-Chou

- [363](https://twreporter-org.atlassian.net/browse/TWREPORTER-363), [364](https://twreporter-org.atlassian.net/browse/TWREPORTER-364): fix style
- [361](https://twreporter-org.atlassian.net/browse/TWREPORTER-361): enter topic page when click `back to topic`
- [356](https://twreporter-org.atlassian.net/browse/TWREPORTER-356): bookmark text should change as status
- [357](https://twreporter-org.atlassian.net/browse/TWREPORTER-357): rename ToolBar to DesktopToolBar as it remove in mobile/tablet
- [360](https://twreporter-org.atlassian.net/browse/TWREPORTER-360): add custom hook to listen click event

2022-06-14 03:49 UTC, duidae requested changes
mostly good & only 2 minor places for code fine tune, thanks.

2022-06-14 03:49 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +  const ref = React.useRef()
could we call `useRef()` and `import {useRef} from 'React'` for consistent style? thanks.

2022-06-14 03:49 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +  React.useEffect(() => {
same as above.

2022-06-16 02:30 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +  const ref = React.useRef()
updated ([839e625](https://github.com/twreporter/twreporter-npm-packages/pull/280/commits/839e625f0986212e415850f6c9db629be301f817))

2022-06-16 02:31 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +  React.useEffect(() => {
updated ([839e625](https://github.com/twreporter/twreporter-npm-packages/pull/280/commits/839e625f0986212e415850f6c9db629be301f817))

2022-06-16 05:40 UTC, duidae approved these changes
LGTM

2022-06-16 05:44 UTC, merged