fix: add id for bookmark & fix icon releaseBranch
twreporter/twreporter-npm-packages pull request #291
Opened 2022-07-20 04:30 UTC by Aylie-Chou

- TWREPORTER-372
  - add `add-bookmark` & `remove-bookmark` id in order to exclude remove bookmark behavior on GTM trigger
- TWREPORTER-398
  - add releaseBranch for desktop-tools icon

2022-07-21 03:32 UTC, duidae requested changes

2022-07-21 03:32 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +        await action()
could we add error handling for action? i.e. `action?.()`

2022-07-21 16:38 UTC, Aylie-Chou commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +        await action()
if `action()` been rejected, it would also be handled by `catch` function in L300.

2022-07-22 02:11 UTC, duidae approved these changes

2022-07-22 02:11 UTC, duidae commented on packages/react-article-components/src/components/aside/mobile-tool-bar.js
> +        await action()
oh i see, thanks.

2022-07-25 06:00 UTC, merged