feat: add hamburger menu
twreporter/twreporter-npm-packages pull request #315
Opened 2022-10-16 17:58 UTC by Aylie-Chou

- [story](https://app.asana.com/0/1202896150264815/1202904767639024/f)
- @twreporter/core 
  - update category-set constant
- @twreporter/react-components
  - add SocialMedia icon
  - add LogoSymbol
- @twreporter/universal-header
  - add HamburgerFooter, HamburgerMenuItem, HamburgerMenu
  - apply feature toggle

The added components shared same utils, thus I cannot split them with different PRs.
I split each components by commits (try my best to make almost every commit has less than 500 diffs)

2022-10-21 06:36 UTC, duidae commented on packages/react-components/src/hook/use-outside-click.js
>      }
kind of curious about this replacement, what would be the benefit for us?

https://stackoverflow.com/questions/2384127/document-onclick-vs-window-onclick

2022-10-21 07:36 UTC, Aylie-Chou commented on packages/react-components/src/hook/use-outside-click.js
>      }
This is because I want to make it work with React [SyntheticEvent](https://reactjs.org/docs/events.html).
ref: https://dev.to/dvnrsn/why-isn-t-event-stoppropagation-working-1bnm

2022-10-21 07:56 UTC, duidae requested changes

2022-10-21 07:56 UTC, duidae commented on packages/universal-header/src/components/hamburger-footer.js
> +        const label = FOOTER_LABEL[key]
we may always need error handling for returned values(`footerLinks`, `link`, `label`), thanks.

2022-10-21 07:56 UTC, duidae commented on packages/universal-header/src/components/hamburger-footer.js
> +        const link = socialMediaLinks[key]
same as above

2022-10-21 07:56 UTC, duidae commented on packages/universal-header/src/components/hamburger-menu.js
> +      const link = getCategoryLink(isLinkExternal, releaseBranch, path)
same as above

2022-10-21 07:56 UTC, duidae commented on packages/universal-header/src/components/hamburger-menu.js
> +      const link = getCategoryLink(isLinkExternal, releaseBranch, path)
same as above

2022-10-21 07:56 UTC, duidae commented on packages/universal-header/src/components/hamburger-menu.js
> +  const itemLinks = getChannelLinks(isLinkExternal, releaseBranch)
same as above

2022-10-24 07:06 UTC, Aylie-Chou commented on packages/react-components/src/hook/use-outside-click.js
>      }
sure, comments added for notice ([eb872aa](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/eb872aa9de69408e4bad58ba7d9c52bfa2f80d1a))

2022-10-24 07:07 UTC, Aylie-Chou commented on packages/universal-header/src/components/hamburger-footer.js
> +        const label = FOOTER_LABEL[key]
add null check before return JSX ([ef8ffa1](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/ef8ffa12fdad73f256f0e76a168a88899f27205f))

2022-10-24 07:07 UTC, Aylie-Chou commented on packages/universal-header/src/components/hamburger-footer.js
> +        const link = socialMediaLinks[key]
add null check before return JSX ([ef8ffa1](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/ef8ffa12fdad73f256f0e76a168a88899f27205f))

2022-10-24 07:07 UTC, Aylie-Chou commented on packages/universal-header/src/components/hamburger-menu.js
> +      const link = getCategoryLink(isLinkExternal, releaseBranch, path)
add null check before return JSX ([ef8ffa1](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/ef8ffa12fdad73f256f0e76a168a88899f27205f))

2022-10-24 07:07 UTC, Aylie-Chou commented on packages/universal-header/src/components/hamburger-menu.js
> +      const link = getCategoryLink(isLinkExternal, releaseBranch, path)
add null check before return JSX ([ef8ffa1](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/ef8ffa12fdad73f256f0e76a168a88899f27205f))

2022-10-24 07:07 UTC, Aylie-Chou commented on packages/universal-header/src/components/hamburger-menu.js
> +  const itemLinks = getChannelLinks(isLinkExternal, releaseBranch)
add null check before return JSX ([ef8ffa1](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/ef8ffa12fdad73f256f0e76a168a88899f27205f))

2022-10-24 07:08 UTC, Aylie-Chou commented
updated ([ef8ffa1](https://github.com/twreporter/twreporter-npm-packages/pull/315/commits/ef8ffa12fdad73f256f0e76a168a88899f27205f))

- add null check for links & labels
- close hamburger menu when change page
- filled in hambuger menu with background color when window > menu height
- fix hamburger menu action button order

Please have a look, thanks.

2022-10-27 09:07 UTC, duidae approved these changes
LGTM! and if PR needs more testing, we can also help :)

2022-10-27 09:18 UTC, merged