fix: defects
twreporter/twreporter-npm-packages pull request #347
Opened 2023-01-03 08:15 UTC by Aylie-Chou

This patch fix defects in this [ticket](https://app.asana.com/0/1202896150264815/1202942985879116/f) & add `@babel/plugin-proposal-optional-catch-binding` to support `try catch` syntax.

2023-01-03 08:29 UTC, duidae requested changes
mostly looking good, but why do we need this package since `@babel/preset-env` already includes this plugin? we could also use try-catch syntax in various subpackages already (react-components, react-article-components...etc)

2023-01-16 07:32 UTC, Aylie-Chou commented
> mostly looking good, but why do we need `@babel/plugin-proposal-optional-catch-binding` since `@babel/preset-env` already includes this plugin? we could also use try-catch syntax in various subpackages already (react-components, react-article-components...etc)

After confirm, we do not need to add this package in additional.
Reverted it at [`4322136`](https://github.com/twreporter/twreporter-npm-packages/pull/347/commits/4322136c88c38229ce8d2528c25e2c675c2ca5b7).

2023-01-16 07:35 UTC, Aylie-Chou commented
Update [`eba130d`](https://github.com/twreporter/twreporter-npm-packages/pull/347/commits/eba130d0d670462ac25f40f25106a364d65fb160) for ios 15.1 only problem.
In ios15.1, url bar would collaspse/uncollapse while scrolling hamburger menu, thus hambuger menu would have change to render shorter height than it need.
This commit add `padding-bottom` for reserved usrl bar height.

2023-01-16 08:41 UTC, duidae approved these changes

2023-01-16 08:55 UTC, merged