Jason/add storybook
twreporter/twreporter-npm-packages pull request #355
Opened 2023-02-07 08:27 UTC by duidae

depend on PR https://github.com/twreporter/twreporter-npm-packages/pull/354

2023-02-09 04:02 UTC, Aylie-Chou commented on packages/react-article-components/src/constants/theme.js
> +// TODO: remove this constant & use @twreporter/core/lib/constants/theme
Question: would we address todo in this pr ?

2023-02-09 09:21 UTC, duidae commented on packages/react-article-components/src/constants/theme.js
> +// TODO: remove this constant & use @twreporter/core/lib/constants/theme
there are tons of places depending on this constant file, better to separate to another PR

2023-02-13 03:15 UTC, Aylie-Chou commented on packages/react-components/src/text/link.js
> +    border-color: ${props => getColorFromTheme(props.theme)};
Could we pass the value of `getColorFromTheme ` into <Text>  if `border-color` shares same value with `color` in L20 invoid calling `getColorFromTheme` twice ?

2023-02-13 03:21 UTC, Aylie-Chou commented on packages/react-components/src/text/link.js
> +  path: PropTypes.string,
Question: would `path` props need to be required ?

2023-02-13 05:06 UTC, Aylie-Chou commented on packages/react-components/src/text/link.js
> +  padding-left: 5px;
As a shared component, I think it would be better to assign `padding` in where you use it.
We could accept `...props` or `className` as <TextLink> prop  to make it a styled-able component.

2023-02-13 05:40 UTC, Aylie-Chou requested changes
Looks like a huge work to unify colors ! I would discuss the color issue with pm & designer for the futher work.
Mostly looking great, just some fine tune for the shared component in react-component.

2023-02-13 06:57 UTC, duidae commented on packages/react-components/src/text/link.js
> +    border-color: ${props => getColorFromTheme(props.theme)};
good point, fixed.

2023-02-13 06:57 UTC, duidae commented on packages/react-components/src/text/link.js
> +  path: PropTypes.string,
fixed.

2023-02-13 06:57 UTC, duidae commented on packages/react-components/src/text/link.js
> +  padding-left: 5px;
fixed.

2023-02-13 06:58 UTC, duidae commented
> Looks like a huge work to unify colors ! I would discuss the color issue with pm & designer for the futher work. Mostly looking great, just some fine tune for the shared component in react-component.

comments are fixed as above, please have a look, thanks.

2023-02-13 09:19 UTC, merged