fix: category politics and society path typo
twreporter/twreporter-npm-packages pull request #357
Opened 2023-02-15 04:13 UTC by Aylie-Chou

This patch fix defect [`[defect] 首頁議題區塊只顯示 7 個區塊，少了政治社會`](https://app.asana.com/0/0/1203964075873158/f)

2023-02-15 09:59 UTC, duidae requested changes

2023-02-15 09:59 UTC, duidae commented on packages/core/src/constants/category-set.js
> -  politicsAndSociety: 'politics-and-society',
also found this string in src/containers/Home.js of `twreporter-react`

2023-02-16 05:46 UTC, Aylie-Chou commented on packages/core/src/constants/category-set.js
> -  politicsAndSociety: 'politics-and-society',
updated ([ec777df](https://github.com/twreporter/twreporter-npm-packages/pull/357/commits/ec777df0caf96f58a0c678db5fff667c6a8481ae))
frontend key name is different from backend api returned key name, thus address key name transform on interface between fe & be (redux)

2023-02-17 10:01 UTC, duidae requested changes

2023-02-17 10:01 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +  try {
I think it would better to check index of array ahead to avoid index out of bound(which could really happen) & using try-catch for error handling

2023-02-18 03:19 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +  try {
The index out of bound case would also catch by try-catch syntax.
The reason not to check out of bound case is that we do not need to split different kind of errors here. (all of the errors should return false)

2023-02-18 03:26 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +  try {
out of bound這種error通常需要被嚴肅對待因為他是有可能造成app crash, 有點好奇用try-catch這樣的招式是從何而來和有何益處, 而且應該是非不得已才使用, 建議還是檢查array index比較正式一點

2023-02-18 05:01 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +  try {
updated. ([68b7ff5](https://github.com/twreporter/twreporter-npm-packages/pull/357/commits/68b7ff54c4c706a6b6eacc7869376f117e46928a))

After checking, I found that javascript arrya is formed by object, thus js array do not have out of bound case, it would return `undefined` for it, so that there's no error throwing for us to catch.
To prevent using more memory here, I change the function to check the index, please have a look.

2023-02-18 05:34 UTC, duidae requested changes

2023-02-18 05:34 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +  try {
then the whole try-catch thing is not necessary, why dont we just
```
const tokens = _.split(pathname, '/')
return tokens?.length >= 2 && tokens[1] === parent
```

2023-02-18 05:44 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +  try {
There's two reason for it.
1. we also need to match and return true for  '/latest/xxx' case
2. Try catch here means a ensure for any other error cases. Ex. input parameter type change

2023-02-18 06:15 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +  try {
updated ([a0c80a7](https://github.com/twreporter/twreporter-npm-packages/pull/357/commits/a0c80a7255ad145884acd1a88eaedc702f7e27c3))

- remove unnecessary try-catch (lodash would handle error here)

2023-02-18 06:23 UTC, duidae approved these changes

2023-02-18 06:23 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +  try {
for 1. we can evaluate the cost of calling `both split() & indexOf()` vs calling only `split()`, leave to you decide.

2023-02-18 06:26 UTC, merged