Jason/subscription components
twreporter/twreporter-npm-packages pull request #367
Opened 2023-03-06 10:14 UTC by duidae

newsletter subscription page related components, [ticket](https://app.asana.com/0/1203699264568808/1203699266233793)

2023-03-07 05:12 UTC, Aylie-Chou requested changes
Mostly looking good.
I found one spec do not been implement, would the change of button components (icons on both left & right hands) be included in this patch ?
![tmp](https://user-images.githubusercontent.com/48147686/223326471-cd22aef2-856e-4ff8-8f97-c7c9902909af.PNG)

2023-03-07 05:12 UTC, Aylie-Chou commented on packages/react-components/src/button/stories/toggleButton.stories.js
> +const Template = args => <ToggleButton {...args} />
Question: toggle button on storybook cannot toggle by click component UI, is it as expected ?

2023-03-07 09:38 UTC, duidae commented on packages/react-components/src/text/headline.js
> +  return headerline
renamed to `headline`

2023-03-07 09:38 UTC, duidae commented on packages/react-components/src/text/paragraph.js
> +    return (
removed.

2023-03-07 09:39 UTC, duidae commented on packages/react-components/src/button/components/toggleButton.js
> +  ...props
added `disabled` prop

2023-03-07 09:39 UTC, duidae commented on packages/react-components/src/button/components/toggleButton.js
> +  label = ['', ''],
renamed to `labelOn` `labelOff`

2023-03-07 09:39 UTC, duidae commented on packages/react-components/src/badge/index.js
> +  background: white;
added color settings

2023-03-07 09:42 UTC, duidae commented on packages/react-components/src/button/stories/toggleButton.stories.js
> +const Template = args => <ToggleButton {...args} />
for simple stateless component, using prop for controlling is sufficient, we dont need to maintain extra inner state

2023-03-07 09:44 UTC, duidae commented
> Mostly looking good. I found one spec do not been implement, would the change of button components (icons on both left & right hands) be included in this patch ? ![tmp](https://user-images.githubusercontent.com/48147686/223326471-cd22aef2-856e-4ff8-8f97-c7c9902909af.PNG)

added change for textbutton, please have a look, thanks.

2023-03-07 09:44 UTC, duidae commented on packages/react-components/src/badge/badge.stories.js
> +  title: 'Badge/Badge',
removed.

2023-03-07 10:50 UTC, Aylie-Chou requested changes

2023-03-07 10:50 UTC, Aylie-Chou commented on packages/react-components/src/button/components/textButton.js
> +  iconPosition: PropTypes.oneOf([Position.LEFT, Position.RIGHT]),
The icon could appear on both left & right side, and each side could have its own icon.

2023-03-07 10:50 UTC, Aylie-Chou commented on packages/react-components/src/button/components/textButton.js
> +  colorSet: PropTypes.shape({
I suppose we control all the color set by `theme`.
Do we add extra color spec this time ?

2023-03-08 03:15 UTC, duidae commented on packages/react-components/src/button/components/textButton.js
> +  iconPosition: PropTypes.oneOf([Position.LEFT, Position.RIGHT]),
fixed.

2023-03-08 03:15 UTC, duidae commented on packages/react-components/src/button/components/textButton.js
> +  colorSet: PropTypes.shape({
fixed with type prop.

2023-03-08 03:46 UTC, Aylie-Chou approved these changes
LGTM, just one more thing also mention in this [comment](https://github.com/twreporter/membership-fe/pull/658#discussion_r1127689158).
I think it's okay if we fix it in next PR.

2023-03-08 06:11 UTC, merged