fix: patch latest & topic on desktop channel
twreporter/twreporter-npm-packages pull request #369
Opened 2023-03-10 06:36 UTC by Aylie-Chou

This patch fix defect [[defect] header 未顯示「最新」、「深度專題」兩個項目](https://app.asana.com/0/1203699264568808/1203964076256284/f)

2023-03-13 07:32 UTC, duidae requested changes

2023-03-13 07:32 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +      CHANNEL_PATH[targetChannelKey]
we may need error handling for `CHANNEL_PATH[targetChannelKey]`

2023-03-14 11:18 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +      CHANNEL_PATH[targetChannelKey]
error handle for parameter `targetChannelKey` added ([cbda297](https://github.com/twreporter/twreporter-npm-packages/pull/369/commits/cbda2974b2b9f54f9d3019aa150fad9bfef46774))
also seperate `getChannelKey` & `getChannelKeys` function.

2023-03-15 03:38 UTC, duidae requested changes

2023-03-15 03:38 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +    throw new Error('invalid channel key')
here we throw the exception but not catching it, seems does not have the effect of error handling, could just copy other js function's handling (ex: find() of array)), return undefined and check the returned value before use

2023-03-15 03:58 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +    throw new Error('invalid channel key')
The parameter `targetChannelKey` would basically use values setting in channel constant file, and would not pass any value from user input, thus I think the throwing error is for the development use.
In this scenario, current code would throw error in twreporter-react SSR. I think it supply enough info for developer to understand where went run.

2023-03-15 06:42 UTC, duidae requested changes

2023-03-15 06:42 UTC, duidae commented on packages/universal-header/src/utils/links.js
> +    throw new Error('invalid channel key')
once we give `getChannelLink` open access to everyone, developers would possibly put anything in the arguments and we may not assume people to know any implicit rule when calling it. We either pull `CHANNEL_PATH` out of this function for clear or properly handle parameters/return value when doing a function call.

2023-03-15 09:55 UTC, Aylie-Chou commented on packages/universal-header/src/utils/links.js
> +    throw new Error('invalid channel key')
updated ([c7856a1](https://github.com/twreporter/twreporter-npm-packages/pull/369/commits/c7856a10811b9053577bcde36aeb73a69c007784))

- add `getLink` to replace `getChannelLink` & `getCategoryLink` function
- add error handle in Channel component

2023-03-16 03:00 UTC, duidae approved these changes

2023-03-16 04:17 UTC, merged