fix: add ArticleCard & CardList component for design guideline
twreporter/twreporter-npm-packages pull request #371
Opened 2023-03-21 15:27 UTC by Aylie-Chou

# Related Issue
This patch address [[defect] 最新頁的 UI 應該是 list，而不是 grid](https://app.asana.com/0/1203699264568808/1203983432530623/f)

# Solution
- add ArticleCard & CardList component (and their stories)
- add icon toggle for TextButton story

2023-03-23 08:03 UTC, Aylie-Chou commented on packages/react-components/src/button/stories/textButton.stories.js
> +textButton.parameters = {
textButton -> toggleIconDisplay

2023-03-24 02:57 UTC, duidae commented on packages/core/src/constants/theme.js
> +export const ARTICLE_THEME = Object.freeze({
(not have change this time) 
for enums, the naming convention would be `camel: { ALL_CAPS }`
https://stackoverflow.com/questions/13233137/javascript-enum-pattern-naming-convention

so I propose we refactor those enum gradually and follow this naming rule for new enums.

2023-03-24 03:02 UTC, duidae commented on packages/react-components/src/button/stories/pillButton.stories.js
> +  SIZE_STORYBOOK_ARG_TYPE,
(not have to change this time)

IMO the storybook-related codes should be encapsulated within the stories/ folder, better not to expose to our codebase in case someone abuse it for convenience in someday

2023-03-24 03:17 UTC, duidae requested changes

2023-03-24 03:17 UTC, duidae commented on packages/react-components/src/button/stories/textButton.stories.js
> +textButton.parameters = {
what does this comment mean?

2023-03-24 03:17 UTC, duidae commented on packages/react-components/src/card/components/article-card.js
> +            <Meta hide={hideMeta}>
some codes produce duplications, like:
```
<Meta hide={hideMeta}>
    {categoryJSX}
     {dateJSX}
</Meta>
```

```
<ImageContainer size={size}>
     <Image
         src={image.src}
          alt={image.alt}
           releaseBranch={releaseBranch}
       />
</ImageContainer>
```

we may remove those duplications to make `size S/L` part a little bit more elegant.

2023-03-24 03:17 UTC, duidae commented on packages/react-components/src/image-with-fallback.js
> +// Vertically and horizontally centering
would this comment be necessary?

2023-03-24 03:17 UTC, duidae commented on packages/react-components/src/image-with-fallback.js
> +class Image extends React.PureComponent {
for what reason we choose `React.PureComponent` here instead of `functional component & hooks` syntax?

2023-03-24 03:17 UTC, duidae commented on packages/react-components/src/listing-page/components/card-list.js
> +        ? entityPaths.interactiveArticle + slug
we probably could use literal templates here
```
to: `${isInteractiveArticle ? entityPaths.interactiveArticle : entityPaths.article}slug`
```

2023-03-24 03:17 UTC, duidae commented on packages/react-components/src/listing-page/components/list.js
> +      const to = isInteractiveArticle
we probably could use literal templates here
```
to: `${isInteractiveArticle ? entityPaths.interactiveArticle : entityPaths.article}slug`
```

2023-03-24 03:18 UTC, duidae commented
mostly looking good, comments are as above, please have a look, thanks.

2023-03-24 06:13 UTC, duidae requested changes

2023-03-24 06:13 UTC, duidae commented on packages/react-components/src/button/constants/index.js
> -export const TEXT_BUTTON_THEME = Object.freeze({
if we move `TEXT_BUTTON_THEME` to packages/core/src/constants/theme.js, we may also need corresponding modifications in repos that have related import, or things would break once this PR is merged.

2023-04-11 09:23 UTC, Aylie-Chou commented on packages/react-components/src/button/constants/index.js
> -export const TEXT_BUTTON_THEME = Object.freeze({
Could you help to check the missing place of import path cuz I couldn't find any 🙏

2023-04-11 10:53 UTC, Aylie-Chou commented on packages/react-components/src/button/stories/textButton.stories.js
> +textButton.parameters = {
`textButton` is the typo (should be `toggleIconDisplay `)
fixed in commit [20c1ebe](https://github.com/twreporter/twreporter-npm-packages/pull/371/commits/20c1ebe273869a176bf2715bc2975fe5abcb50b6)

2023-04-11 10:53 UTC, Aylie-Chou commented on packages/react-components/src/card/components/article-card.js
> +            <Meta hide={hideMeta}>
updated [20c1ebe](https://github.com/twreporter/twreporter-npm-packages/pull/371/commits/20c1ebe273869a176bf2715bc2975fe5abcb50b6)

2023-04-11 10:54 UTC, Aylie-Chou commented on packages/core/src/constants/theme.js
> +export const ARTICLE_THEME = Object.freeze({
I would add refactor for enum in PR #375

2023-04-11 10:54 UTC, Aylie-Chou commented on packages/react-components/src/button/stories/pillButton.stories.js
> +  SIZE_STORYBOOK_ARG_TYPE,
Sure, this would also be covered in #375

2023-04-12 01:46 UTC, Aylie-Chou commented on packages/react-components/src/image-with-fallback.js
> +class Image extends React.PureComponent {
Updated image-with-fallback into function component ([854edb7](https://github.com/twreporter/twreporter-npm-packages/pull/371/commits/854edb7631b64087f7959105ca642fdb347a48fc))
The reason we need a new image fallback component is that we decide to move all assets on gcs (old method stores assets in local) My plan is to gradually migrate other code to use the new image fallback.

2023-04-12 01:46 UTC, Aylie-Chou commented on packages/react-components/src/listing-page/components/card-list.js
> +        ? entityPaths.interactiveArticle + slug
sure, updated. ([539cac0](https://github.com/twreporter/twreporter-npm-packages/pull/371/commits/539cac05e06e33621a9fbc4b9971e040c4560bf8))

2023-04-12 02:20 UTC, duidae commented on packages/react-components/src/button/constants/index.js
> -export const TEXT_BUTTON_THEME = Object.freeze({
should be in `membership-fe`

2023-04-12 03:13 UTC, Aylie-Chou commented on packages/react-components/src/image-with-fallback.js
> +// Vertically and horizontally centering
updated ([854edb7](https://github.com/twreporter/twreporter-npm-packages/pull/371/commits/854edb7631b64087f7959105ca642fdb347a48fc))

2023-04-12 07:14 UTC, duidae commented on packages/react-components/src/image-with-fallback.js
> +class Image extends React.PureComponent {
`react-components/src/image-with-fallback.js` is almost the same with `react-components/src/listing-page/components/image.js`, we may also need to reduce the duplication here.

2023-04-12 07:22 UTC, duidae requested changes

2023-04-12 07:22 UTC, duidae commented on packages/react-components/src/image-with-fallback.js
> +import React, { useState, useEffect, useRef } from 'react'
`react-components/src/image-with-fallback.js` is almost the same with `react-components/src/listing-page/components/image.js`, we may also need to reduce the duplication here.

2023-04-12 09:23 UTC, Aylie-Chou commented on packages/react-components/src/button/constants/index.js
> -export const TEXT_BUTTON_THEME = Object.freeze({
updated at membership-fe [#684](https://github.com/twreporter/membership-fe/pull/684)

2023-04-13 02:19 UTC, duidae commented on packages/react-components/src/image-with-fallback.js
> +class Image extends React.PureComponent {
could we add comments in `react-components/src/listing-page/components/image.js` to address this thing is going to phase out & use `react-components/src/image-with-fallback.js` instead.

2023-04-13 02:30 UTC, duidae requested changes

2023-04-13 02:36 UTC, duidae requested changes

2023-04-13 02:36 UTC, duidae commented on packages/react-components/src/image-with-fallback.js
> +import React, { useState, useEffect, useRef } from 'react'
could we add comments to address `react-components/src/image-with-fallback.js` is going to phase out and use `react-components/src/listing-page/components/image.js` instead.

2023-04-13 02:46 UTC, Aylie-Chou commented on packages/react-components/src/image-with-fallback.js
> +import React, { useState, useEffect, useRef } from 'react'
sure, added ([c5db49d](https://github.com/twreporter/twreporter-npm-packages/pull/371/commits/c5db49dc1fae29527e7dec334bcadba18068aea4))

2023-04-13 05:31 UTC, duidae approved these changes

2023-04-13 05:50 UTC, merged