Jason/subscription 2 checkbox
twreporter/twreporter-npm-packages pull request #374
Opened 2023-03-25 03:09 UTC by duidae

# Related Issue

https://app.asana.com/0/1203699264568808/1203762836596954/f

# Root Cause

# Solution

2023-04-11 03:39 UTC, Aylie-Chou commented
Based on the design, the checkbox background color would need to be transparent when value is false.

// current code on storybook
<img width="88" alt="螢幕截圖 2023-04-11 上午11 37 36" src="https://user-images.githubusercontent.com/48147686/231050001-ca27b6da-0168-453b-b408-1ec49cf4ccef.png">

// design
<img width="571" alt="螢幕截圖 2023-04-11 上午11 37 55" src="https://user-images.githubusercontent.com/48147686/231050004-fe8d29ae-6b8a-416d-9946-f234e9cdddab.png">

2023-04-11 03:49 UTC, Aylie-Chou requested changes

2023-04-11 03:49 UTC, Aylie-Chou commented on packages/react-components/src/checkbox/checkbox.stories.js
> +  onChange: () => {},
Could we add a story about how `onChange` works (ex. alert checked/uncheck ) ?

2023-04-11 03:49 UTC, Aylie-Chou commented on packages/react-components/src/button/utils/theme.js
> +        color: colorBrand.dark,
question: why would we need to change color here ? (the changed color seems not match with design)

2023-04-11 03:49 UTC, Aylie-Chou commented on packages/react-components/src/checkbox/index.js
> +    onChange && onChange()
may we pass event(`e`) in to onChange function

2023-04-12 02:14 UTC, duidae commented on packages/react-components/src/checkbox/index.js
> +    onChange && onChange()
added

2023-04-12 02:14 UTC, duidae commented
> Based on the design, the checkbox background color would need to be transparent when value is false.
> 
> // current code on storybook <img alt="螢幕截圖 2023-04-11 上午11 37 36" width="88" src="https://user-images.githubusercontent.com/48147686/231050001-ca27b6da-0168-453b-b408-1ec49cf4ccef.png">
> 
> // design <img alt="螢幕截圖 2023-04-11 上午11 37 55" width="571" src="https://user-images.githubusercontent.com/48147686/231050004-fe8d29ae-6b8a-416d-9946-f234e9cdddab.png">

fixed, please have a look, thanks.

2023-04-12 02:26 UTC, Aylie-Chou commented on packages/react-components/src/button/utils/theme.js
> +        color: colorBrand.dark,
found it !

2023-04-12 02:28 UTC, Aylie-Chou approved these changes
LGTM

2023-04-12 02:45 UTC, merged