16 feature add design guideline component
twreporter/twreporter-npm-packages pull request #375
Opened 2023-03-30 09:02 UTC by Aylie-Chou

# Issue
[[會員制] 登入頁、註冊頁](https://app.asana.com/0/1203699264568808/1204190744160592/f)

# Change
- add Letter, Google icon component
- add LinkButton component with storybook
  - migrate text/link to LinkButton
- adjust PillButton style
  - add leftIconComponent & rightIconComponent
  - delete iconComponent
- refactor Icon component

# Dependency
N/A

2023-04-06 02:42 UTC, duidae requested changes

2023-04-06 02:42 UTC, duidae commented on packages/core/src/constants/color.js
> +export const COLOR_SEMANTIC = Object.freeze({
like mentioned in https://github.com/twreporter/twreporter-npm-packages/pull/371#discussion_r1147069279

we may apply the suggested naming convention for new enums

2023-04-06 02:42 UTC, duidae commented on packages/react-article-components/src/components/aside/metadata.js
> +          <TextLink link={link} text={name} weight={weight} />
we may replace literals `'bold'`, `'normal'` with `WEIGHT.normal`, `WEIGHT.bold`

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/icon/stories/socialMedia.stories.js
> +import { BRANCH_STORYBOOK_ARG_TYPE } from '@twreporter/core/lib/constants/release-branch'
same as above

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/icon/stories/letter.stories.js
> +import { BRANCH_STORYBOOK_ARG_TYPE } from '@twreporter/core/lib/constants/release-branch'
like mentioned in https://github.com/twreporter/twreporter-npm-packages/pull/371#discussion_r1147071151
we may not expose the storybook-related codes to our main codebase for better encapsulation

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/button/components/link.js
> +  weight: PropTypes.string,
we may use something like `weight: WEIGHT_PROP_TYPES,`

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/button/constants/type.js
> +export const LINK_TYPE = Object.freeze({
same as https://github.com/twreporter/twreporter-npm-packages/pull/371#discussion_r1147069279

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/button/constants/type.js
> +export const LINK_TYPE_STORYBOOK_ARG_TYPE = {
same as above

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/button/constants/style.js
> +export const STYLE = Object.freeze({
same as https://github.com/twreporter/twreporter-npm-packages/pull/371#discussion_r1147069279

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/button/constants/style.js
> +export const STYLE_STORYBOOK_ARG_TYPE = {
same as above

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/icon/index.js
> +  type = 'mask',
could we give a enum for `mask`, `raw` to avoid using pure literals directly in props definition?

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/icon/index.js
> +    type: PropTypes.oneOf(['mask', 'raw']),
we may reduce duplicate code `['mask', 'raw']` here

2023-04-06 02:42 UTC, duidae commented on packages/react-components/src/button/components/link.js
> +  weight,
could we have default value for `weight`?

2023-04-14 04:11 UTC, Aylie-Chou commented on packages/core/src/constants/color.js
> +export const COLOR_SEMANTIC = Object.freeze({
IMO, `COLOR_SEMANTIC` is a constant, thus would follow const export convention.

2023-04-14 05:08 UTC, Aylie-Chou commented
updated ([fadd2a5](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/fadd2a5e963a3fa6f55dbcba82f1dc3b5c03b6d2), [2e0ff41](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/2e0ff41dec714b4a9c97a02027dc4fdb91c958b9), [4d22736](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/4d22736f409a002537d1912300ff911197582729))

- [fadd2a5](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/fadd2a5e963a3fa6f55dbcba82f1dc3b5c03b6d2)
  - refactor `enum` use based on [this guide](https://www.notion.so/twreporter/React-component-enum-props-best-practice-e3d8085163374f96a129e236598990f3?pvs=4)
-  [2e0ff41](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/2e0ff41dec714b4a9c97a02027dc4fdb91c958b9)
  - use component defined enum in react-article-componet
- [4d22736](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/4d22736f409a002537d1912300ff911197582729)
  - remove storybook related const from core package
  
  Please have a look, thanks.

2023-04-17 08:54 UTC, duidae requested changes
mostly looking good, there is only 1 issue about the name we export here, we use camel starting with lowercase for enums & constants:

```
IconButton.theme = THEME
IconButton.type = Type
```

could we keep the naming convention to show the identity of variables when exporting:

```
IconButton.THEME = THEME
IconButton.Type = Type
```

so that we can understand the role of the member instantly, i.e. in `IconButton.THEME`, THEME is all capital so it must be a constant of IconButton; in `IconButton.Type`, Type is camel starting uppercase so it must be a enum of IconButton.

2023-04-18 06:12 UTC, Aylie-Chou commented
good idea, updated [022d112](https://github.com/twreporter/twreporter-npm-packages/pull/375/commits/022d112baa7001db775b55ef604e909aa7f76462)
Please have a look.

2023-04-18 07:50 UTC, duidae approved these changes

2023-04-18 08:10 UTC, merged