Feature/add under construction
twreporter/twreporter-npm-packages pull request #381
Opened 2023-04-25 11:12 UTC by liruchen32

# Issue
[[會員制] 贊助紀錄頁 under construction（前端） ](https://app.asana.com/0/1203699264568808/1204362012792374/f)

# Notice
目前 bookmark 的圖片還是使用舊的連結

# Dependency

2023-04-27 09:29 UTC, Aylie-Chou requested changes
Good catch for the storybook usage !
I've leaved some comments for u, please have a look.

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +import releaseBranchConsts from '@twreporter/core/lib/constants/release-branch'
Could we use the new defined const `{ BRANCH, BRANCH_PROP_TYPES } `  defined in core/lib/constants/release-branch here ?

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +      return `https://www.twreporter.org/assets/bookmark/${releaseBranch}/seek.png`
Question: why do we need to use old assets path for bookmark ?

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +        BookMarkContainer(releaseBranch)
Could we combine bookmark & general use code since they have many places look alike ?
(Maybe we could make this component more general ex. accept `component` as `guide` props)

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +            <P1 text={title} weight="bold" />
May we use defined enum for weight prop value
```
<P1 text={title} weight={P1.Weight.BOLD} />

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +              <PillButton text={buttonText} size="L" />
May we use defined enum for size prop value ?

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +  style: PropTypes.oneOf(Object.values(Style)),
May we also export enums on `EmptyState` component ?

2023-04-27 09:29 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/stories/empty-guide.stories.js
> +    releaseBranch: getRadioArg([master, staging, preview, release], master),
Could we use defined `BRANCH_STORYBOOK_ARG_TYPES` in storybook/constants here ?

2023-04-27 09:46 UTC, liruchen32 commented on packages/react-components/src/empty-state/index.js
> +import releaseBranchConsts from '@twreporter/core/lib/constants/release-branch'
fixed

2023-04-27 09:47 UTC, liruchen32 commented on packages/react-components/src/empty-state/index.js
> +      return `https://www.twreporter.org/assets/bookmark/${releaseBranch}/seek.png`
my bad

2023-04-27 09:47 UTC, liruchen32 commented on packages/react-components/src/empty-state/index.js
> +            <P1 text={title} weight="bold" />
fixed

2023-04-27 09:51 UTC, liruchen32 commented on packages/react-components/src/empty-state/index.js
> +              <PillButton text={buttonText} size="L" />
fixed

2023-04-27 09:51 UTC, liruchen32 commented on packages/react-components/src/empty-state/stories/empty-guide.stories.js
> +  title: 'Empty State/Empty State',
fixed

2023-05-02 06:27 UTC, liruchen32 commented on packages/react-components/src/empty-state/index.js
> +        BookMarkContainer(releaseBranch)
fixed

2023-05-03 03:12 UTC, Aylie-Chou commented on packages/react-components/src/bookmark-list/bookmarks.js
> +            <BookMarkIcon type="add" releaseBranch={releaseBranch} />
May we use defined enum as type prop value here

2023-05-03 03:14 UTC, Aylie-Chou commented on packages/react-components/src/empty-state/index.js
> +    case Style.DEFAULT:
Since `Style.DEFAULT` return same url with `default` case, we could combine them as below:
```
case Style.DEFAULT:
default:
  return `https://xxx.xxx.xxx`

2023-05-03 03:16 UTC, Aylie-Chou commented
Mostly looking good 👍
Just few comments to solve, then we would move on !

2023-05-03 04:57 UTC, liruchen32 commented on packages/react-components/src/bookmark-list/bookmarks.js
> +            <BookMarkIcon type="add" releaseBranch={releaseBranch} />
fixed

2023-05-03 04:57 UTC, liruchen32 commented on packages/react-components/src/empty-state/index.js
> +    case Style.DEFAULT:
fixed

2023-05-04 03:22 UTC, Aylie-Chou approved these changes
LGTM

2023-05-05 05:15 UTC, merged