Feature/reading analytics api
twreporter/twreporter-npm-packages pull request #475
Opened 2023-12-19 06:52 UTC by liruchen32

# Issue
[[會員制] 閱讀文章篇數、閱讀時間串接](https://app.asana.com/0/1203699264568808/1206008027632075/f)

# Notice

# Dependency

2023-12-25 09:25 UTC, Aylie-Chou commented on packages/redux/src/actions/__test__/analytics.test.js
> +    test('should dispatch an action created by `setUserAnalyticsData` if updating failed', () => {
Could we also add some cases for `400` & `401` errors

2023-12-26 06:53 UTC, Aylie-Chou requested changes
Mostly looking gooood !
As previous discussion, it would be great to also add fail test cases for `400` errors, please have a look.

2023-12-26 08:33 UTC, liruchen32 commented on packages/redux/src/actions/__test__/analytics.test.js
> +    test('should dispatch an action created by `setUserAnalyticsData` if updating failed', () => {
fixed

2023-12-26 08:39 UTC, Aylie-Chou approved these changes
LGTM

2023-12-26 08:41 UTC, merged