Feature/user footprint api
twreporter/twreporter-npm-packages pull request #498
Opened 2024-01-29 09:59 UTC by liruchen32

# Issue
[[會員制] 我的閱讀：造訪紀錄串接](https://app.asana.com/0/1203699264568808/1206379511127434/f)

# Notice

# Dependency
[go-api#665](https://github.com/twreporter/go-api/pull/665)

2024-02-07 07:34 UTC, Aylie-Chou commented on packages/core/src/constants/prop-types.js
> +  post_id: PropTypes.string,
could we also add `category` prop type here XD

2024-02-07 07:38 UTC, Aylie-Chou commented on packages/redux/src/actions/__test__/mocks/footprints.js
> +      is_external: false,
could we also add `bookmark_id` key in mock data

2024-02-07 07:41 UTC, Aylie-Chou commented on packages/redux/src/actions/footprints.js
> +export function getUserFootprints(jwt, userID, offset, limit) {
could we add default value for offset & limit
ex. limit = 10, offset = 0

2024-02-07 07:43 UTC, Aylie-Chou commented on packages/redux/src/reducers/__test__/mocks/footprints.js
> +            is_external: false,
same as this [comment](https://github.com/twreporter/twreporter-npm-packages/pull/498/files#r1481009851)

2024-02-07 07:48 UTC, Aylie-Chou requested changes
Great work to build up footprint actions & reducers 👍
Please have a look at comments for some details to check.

Also if the footprints state would handle `bookmark` related state, that state should also be updated when bookmark been created or deleted in other places.
Please also help to check this part 🙏

2024-02-07 08:47 UTC, liruchen32 commented on packages/core/src/constants/prop-types.js
> +  post_id: PropTypes.string,
fixed

2024-02-07 08:48 UTC, liruchen32 commented on packages/redux/src/actions/__test__/footprints.test.js
> +    test('should dispatch an action created by `getUserFootprints` if updating failed', () => {
fixed

2024-02-07 08:50 UTC, liruchen32 commented on packages/redux/src/actions/__test__/mocks/footprints.js
> +      is_external: false,
fixed

2024-02-07 08:51 UTC, liruchen32 commented on packages/redux/src/actions/footprints.js
> +export function getUserFootprints(jwt, userID, offset, limit) {
fixed

2024-02-07 08:51 UTC, liruchen32 commented on packages/redux/src/reducers/__test__/mocks/footprints.js
> +            is_external: false,
fixed

2024-02-07 09:11 UTC, Aylie-Chou commented on packages/redux/src/actions/__test__/mocks/footprints.js
> +      is_external: false,
bookmark_id would be a string

2024-02-07 09:12 UTC, Aylie-Chou requested changes
as comment ~~

2024-02-15 06:09 UTC, Aylie-Chou approved these changes
LGTM

2024-02-15 06:20 UTC, merged