Feature/post review api
twreporter/twreporter-npm-packages pull request #533
Opened 2024-04-29 04:09 UTC by liruchen32

# Issue
[[會員制]重要報導回顧-串接](https://app.asana.com/0/1203699264568808/1206721264374718/f)

# Notice

# Dependency

2024-05-07 06:52 UTC, Aylie-Chou commented on packages/redux/src/actions/__test__/post-reviews.test.js
> +  describe(`Test action getUserFootprints`, () => {
user footprints -> post reviews

2024-05-07 06:53 UTC, Aylie-Chou commented on packages/redux/src/actions/__test__/post-reviews.test.js
> +    test('should dispatch an action created by `getUserFootprints` if fetching successed', () => {
same as [this comment](https://github.com/twreporter/twreporter-npm-packages/pull/533/files#r1591900800)

2024-05-07 06:53 UTC, Aylie-Chou commented on packages/redux/src/actions/__test__/post-reviews.test.js
> +    test('should dispatch an action created by `getUserFootprints` if fetching failed', () => {
same as [this comment](https://github.com/twreporter/twreporter-npm-packages/pull/533/files#r1591900800)

2024-05-07 06:54 UTC, Aylie-Chou commented on packages/redux/src/actions/post-reviews.js
> + * get user's donation history
could we also update the comment to post review version XD

2024-05-07 06:57 UTC, Aylie-Chou requested changes
mostly looking good~~
just some copy paste stuff to fix

2024-05-07 09:55 UTC, liruchen32 commented on packages/redux/src/actions/__test__/post-reviews.test.js
> +  describe(`Test action getUserFootprints`, () => {
fixed

2024-05-07 09:55 UTC, liruchen32 commented on packages/redux/src/actions/__test__/post-reviews.test.js
> +    test('should dispatch an action created by `getUserFootprints` if fetching successed', () => {
fixed

2024-05-07 09:55 UTC, liruchen32 commented on packages/redux/src/actions/__test__/post-reviews.test.js
> +    test('should dispatch an action created by `getUserFootprints` if fetching failed', () => {
fixed

2024-05-07 09:56 UTC, liruchen32 commented on packages/redux/src/actions/post-reviews.js
> + * get user's donation history
fixed

2024-05-07 18:34 UTC, Aylie-Chou requested changes
漏網之魚！

2024-05-08 06:16 UTC, liruchen32 commented on packages/redux/src/actions/post-reviews.js
> + * get user's donation history
fixed

2024-05-08 07:13 UTC, Aylie-Chou approved these changes
LGTM

2024-05-08 07:26 UTC, merged